language: cpp
dist: xenial

before_install:
- sudo apt-get install -y gfortran
- export SPACK_ROOT=$HOME/.cache/spack
- export PATH=$PATH:$HOME/.cache/spack/bin

install:
- if ! which spack >/dev/null; then
  mkdir -p $SPACK_ROOT &&
  git clone --depth 50 https://github.com/spack/spack.git $SPACK_ROOT &&
  echo -e "config:""\n  build_jobs:"" 2" > $SPACK_ROOT/etc/spack/config.yaml;
  fi
- spack compilers
- spack spec openmpi %gcc@5.4.0
- travis_wait 50 spack install openmpi %gcc@5.4.0
- spack spec boost %gcc@5.4.0
- travis_wait 50 spack install boost %gcc@5.4.0

before_script:
- mkdir build
- cd build
- cmake ..

script: make